Document: glslang
Title: Debian glslang Manual
Author: <insert document author here>
Abstract: This manual describes what glslang is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/glslang/glslang.sgml.gz

Format: postscript
Files: /usr/share/doc/glslang/glslang.ps.gz

Format: text
Files: /usr/share/doc/glslang/glslang.text.gz

Format: HTML
Index: /usr/share/doc/glslang/html/index.html
Files: /usr/share/doc/glslang/html/*.html
